
// Do not edit this file; automatically generated by build.py.
'use strict';

const jsdom = require("jsdom");
const { JSDOM } = jsdom;
const dom  = new JSDOM(``);
global.window= dom.window;
global.document = dom.window.document;

const jsblockly = require("blockly/blockly_uncompressed.js");
