// Code generated by "stringer -type=InputType"; DO NOT EDIT.

package gblocks

import "fmt"

const _InputType_name = "InputValueOutputValueNextStatementPreviousStatementDummyInput"

var _InputType_index = [...]uint8{0, 10, 21, 34, 51, 61}

func (i InputType) String() string {
	i -= 1
	if i < 0 || i >= InputType(len(_InputType_index)-1) {
		return fmt.Sprintf("InputType(%d)", i+1)
	}
	return _InputType_name[_InputType_index[i]:_InputType_index[i+1]]
}
