// Code generated by "stringer -type=InputAlign"; DO NOT EDIT.

package gblocks

import "fmt"

const _InputAlign_name = "AlignLeftAlignCentreAlignRight"

var _InputAlign_index = [...]uint8{0, 9, 20, 30}

func (i InputAlign) String() string {
	i -= -1
	if i < 0 || i >= InputAlign(len(_InputAlign_index)-1) {
		return fmt.Sprintf("InputAlign(%d)", i+-1)
	}
	return _InputAlign_name[_InputAlign_index[i]:_InputAlign_index[i+1]]
}
