// Code generated by "stringer -type=Possessives"; DO NOT EDIT.
package gblocks

import "fmt"

const _Possessives_name = "IsAIsAnAreAnAreAreA"

var _Possessives_index = [...]uint8{0, 3, 7, 12, 15, 19}

func (i Possessives) String() string {
	if i < 0 || i >= Possessives(len(_Possessives_index)-1) {
		return fmt.Sprintf("Possessives(%d)", i)
	}
	return _Possessives_name[_Possessives_index[i]:_Possessives_index[i+1]]
}
