// Code generated by "stringer -type=Class"; DO NOT EDIT.

package inspect

import "fmt"

const _Class_name = "UnknownBoolIntUintFloatLabelTextDateGroupInputStatementsNextLinkPrevLink"

var _Class_index = [...]uint8{0, 7, 11, 14, 18, 23, 28, 32, 36, 41, 46, 56, 64, 72}

func (i Class) String() string {
	if i < 0 || i >= Class(len(_Class_index)-1) {
		return fmt.Sprintf("Class(%d)", i)
	}
	return _Class_name[_Class_index[i]:_Class_index[i+1]]
}
