// Code generated by "stringer -type=InputType"; DO NOT EDIT.

package blockly

import "fmt"

const _InputType_name = "InputValueTypeOutputValueTypeNextStatementTypePreviousStatementTypeDummyInputType"

var _InputType_index = [...]uint8{0, 14, 29, 46, 67, 81}

func (i InputType) String() string {
	i -= 1
	if i < 0 || i >= InputType(len(_InputType_index)-1) {
		return fmt.Sprintf("InputType(%d)", i+1)
	}
	return _InputType_name[_InputType_index[i]:_InputType_index[i+1]]
}
