// Code generated by "stringer -type=Class"; DO NOT EDIT.

package tin

import "fmt"

const _Class_name = "UnknownBoolIntUintFloatTextDateInputClass"

var _Class_index = [...]uint8{0, 7, 11, 14, 18, 23, 27, 31, 41}

func (i Class) String() string {
	if i < 0 || i >= Class(len(_Class_index)-1) {
		return fmt.Sprintf("Class(%d)", i)
	}
	return _Class_name[_Class_index[i]:_Class_index[i+1]]
}
