// Code generated by "stringer -type=Class"; DO NOT EDIT.

package tin

import "fmt"

const _Class_name = "UnknownClassBoolIntUintFloatTextDateOptionInputClass"

var _Class_index = [...]uint8{0, 12, 16, 19, 23, 28, 32, 36, 42, 52}

func (i Class) String() string {
	if i < 0 || i >= Class(len(_Class_index)-1) {
		return fmt.Sprintf("Class(%d)", i)
	}
	return _Class_name[_Class_index[i]:_Class_index[i+1]]
}
